# Generated by Django 5.2.13 on 2026-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='date_inscription',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
